// TradeX AI public demonstration — entirely synthetic, deterministic values.
// No market feeds, accounts, payments, or personal data are transferred to a server.
'use strict';
const instruments = [
  {symbol:'DEMO-A',name:'Example Industries',base:1240,seed:17},
  {symbol:'DEMO-B',name:'Practice Technologies',base:785,seed:91},
  {symbol:'DEMO-C',name:'Sample Banking',base:1635,seed:42}
];
const STORAGE='tradex_public_preview_v1';
const startBalance=100000;
const state={symbol:instruments[0],interval:5,pro:false, cash:startBalance, positions:{}, history:[]};
const fmt=n=>'₹'+Number(n).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const el=id=>document.getElementById(id);
let baseSeries=[];let visibleSeries=[];
function randFactory(seed){let v=seed;return ()=>{v=(v*16807)%2147483647;return (v-1)/2147483646;}}
function generate(inst){
  const rnd=randFactory(inst.seed),arr=[];let last=inst.base;
  // Each bar is a fictional 5-minute interval, from 09:15 to 15:10 IST.
  for(let i=0;i<72;i++){
    const volatility=inst.base*.0028;const open=last;
    const close=Math.max(20,open+(rnd()-.48)*volatility*2);
    const high=Math.max(open,close)+rnd()*volatility;
    const low=Math.min(open,close)-rnd()*volatility;
    arr.push({minutes:555+i*5,open,high,low,close});last=close;
  }return arr;
}
function aggregate(arr,interval){let group=interval/5;let out=[];for(let i=0;i<arr.length;i+=group){let slice=arr.slice(i,i+group);if(!slice.length)break;out.push({minutes:slice[0].minutes,open:slice[0].open,close:slice[slice.length-1].close,high:Math.max(...slice.map(x=>x.high)),low:Math.min(...slice.map(x=>x.low))});}return out;}
function timeLabel(minutes){let h=Math.floor(minutes/60),m=minutes%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;}
function lastPrice(inst){return generate(inst).at(-1).close;}
function safeStore(){try{localStorage.setItem(STORAGE,JSON.stringify({cash:state.cash,positions:state.positions,history:state.history,pro:state.pro}));}catch(e){/* unavailable storage is non-fatal */}}
function loadStore(){try{const x=JSON.parse(localStorage.getItem(STORAGE)||'null');if(!x||typeof x!=='object')return;if(typeof x.cash==='number'&&Number.isFinite(x.cash)&&x.cash>=0&&x.cash<=1e8)state.cash=x.cash;if(x.positions&&typeof x.positions==='object'){for(const inst of instruments){let qty=Number(x.positions[inst.symbol]);if(Number.isSafeInteger(qty)&&qty>=0&&qty<=1e6)state.positions[inst.symbol]=qty;}}if(Array.isArray(x.history))state.history=x.history.slice(0,20).filter(t=>t&&typeof t.symbol==='string'&&Number.isFinite(t.price));state.pro=x.pro===true;}catch(e){/* ignore invalid local preview */}}
function setupStocks(){el('symbol-list').innerHTML='';for(let inst of instruments){let button=document.createElement('button');button.type='button';button.className='symbol'+(state.symbol===inst?' selected':'');button.innerHTML=`<span><strong>${inst.symbol}</strong><small>${inst.name}</small></span><span class="symbol-price">${fmt(lastPrice(inst))}</span>`;button.addEventListener('click',()=>{state.symbol=inst;setupStocks();updateAll();});el('symbol-list').append(button);}}
function linePath(vals,width,height,padding=5){const low=Math.min(...vals),high=Math.max(...vals),range=Math.max(high-low,1);return vals.map((y,i)=>`${i?'L':'M'} ${padding+(i/(vals.length-1))*(width-padding*2)} ${padding+(1-(y-low)/range)*(height-padding*2)}`).join(' ');}
function updateHeader(){const inst=state.symbol,series=generate(inst),last=series.at(-1).close,first=series[0].open,pct=(last/first-1)*100;el('symbol-name').textContent=inst.name;el('symbol-code').textContent=inst.symbol+' • FICTIONAL INSTRUMENT';el('last-price').textContent=fmt(last);el('sample-change').textContent=(pct>=0?'+':'')+pct.toFixed(2)+'% sample change';el('sample-change').style.color=pct>=0?'#2de4aa':'#ff6e81';el('hero-price').textContent=fmt(lastPrice(instruments[0]));let hero=generate(instruments[0]).map(x=>x.close);el('hero-spark').innerHTML=`<svg viewBox="0 0 350 110" preserveAspectRatio="none"><defs><linearGradient id="fade" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#35deb1" stop-opacity=".3"/><stop offset="1" stop-color="#35deb1" stop-opacity="0"/></linearGradient></defs><path d="${linePath(hero,350,100,4)} L346,106 L4,106 Z" fill="url(#fade)"/><path d="${linePath(hero,350,100,4)}" stroke="#31dfac" fill="none" stroke-width="2.3"/></svg>`;}
function seriesForChart(){baseSeries=generate(state.symbol);visibleSeries=aggregate(baseSeries,state.interval);}
function drawChart(){const canvas=el('chart'),parent=canvas.parentElement;let rect=parent.getBoundingClientRect();const w=Math.max(260,rect.width),h=Math.max(205,rect.height),dpr=Math.max(1,window.devicePixelRatio||1);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const left=8,right=79,top=13,bottom=31,plotW=w-left-right,plotH=h-top-bottom;let lows=visibleSeries.map(d=>d.low),highs=visibleSeries.map(d=>d.high);const min=Math.min(...lows),max=Math.max(...highs),pad=(max-min)*.13||5,lo=min-pad,hi=max+pad,y=v=>top+(1-(v-lo)/(hi-lo))*plotH;ctx.font='11px system-ui';ctx.textBaseline='middle';ctx.strokeStyle='#294057';ctx.lineWidth=1;for(let i=0;i<5;i++){let val=lo+(hi-lo)*i/4,yy=y(val);ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(left+plotW,yy);ctx.stroke();ctx.fillStyle='#91a9c0';ctx.fillText('₹'+val.toFixed(1),left+plotW+8,yy);}const stride=plotW/visibleSeries.length,body=Math.min(13,Math.max(2,stride*.64));visibleSeries.forEach((d,i)=>{let x=left+stride*(i+.5),rise=d.close>=d.open;ctx.strokeStyle=rise?'#37dfac':'#ef6f85';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(x,y(d.low));ctx.lineTo(x,y(d.high));ctx.stroke();let yt=y(Math.max(d.open,d.close)),yb=y(Math.min(d.open,d.close));ctx.fillRect(x-body/2,yt,body,Math.max(1.4,yb-yt));});ctx.fillStyle='#88a3ba';ctx.textBaseline='top';for(let i=0;i<5;i++){let index=Math.floor(i*(visibleSeries.length-1)/4),d=visibleSeries[index],x=left+stride*(index+.5);ctx.fillText(timeLabel(d.minutes),Math.min(w-130,Math.max(6,x-14)),h-bottom+8);}if(state.pro){let closes=visibleSeries.map(v=>v.close);ctx.strokeStyle='#73a5fa';ctx.lineWidth=1.8;ctx.beginPath();closes.forEach((v,i)=>{if(i<Math.min(20,closes.length)-1)return;let avg=closes.slice(Math.max(0,i-19),i+1).reduce((a,b)=>a+b,0)/Math.min(i+1,20),x=left+stride*(i+.5),yy=y(avg);if(i===Math.min(20,closes.length)-1)ctx.moveTo(x,yy);else ctx.lineTo(x,yy);});ctx.stroke();}canvas._chartGeom={left,right,plotW,stride};}
function updateTrading(){const access=el('access-label');access.textContent=state.pro?'SAMPLE PRO • ACTIVE':'FREE • VIEW ONLY';access.style.color=state.pro?'#2de4aa':'';el('access-message').textContent=state.pro?'Public feature preview: sample trades stay only in this browser. No paid access is being granted.':'Buy and Sell are locked on Free. Select the sample Pro preview to try the interface.';el('free-button').classList.toggle('toggle-on',!state.pro);el('pro-button').classList.toggle('toggle-on',state.pro);el('buy-button').disabled=!state.pro;el('sell-button').disabled=!state.pro;el('reset-button').disabled=!state.pro;el('indicator-line').textContent=state.pro?'Sample Pro indicator: blue line shows a simple 20-bar moving average. No live market information.':'Indicators: Sample Pro preview only.';}
function updatePortfolio(){el('wallet').textContent=fmt(state.cash);let invested=0,markup='';for(const inst of instruments){let qty=state.positions[inst.symbol]||0;if(qty){let mark=lastPrice(inst)*qty;invested+=mark;markup+=`<div class="position"><span>${inst.symbol} × ${qty}</span><strong>${fmt(mark)}</strong></div>`;}}el('positions').innerHTML=markup||'No sample trades yet.';el('invested').textContent=fmt(invested);el('equity').textContent=fmt(invested+state.cash);let box=el('history');box.textContent='';if(!state.history.length){box.textContent='No sample orders yet. Switch to sample Pro and make a virtual trade.';return;}for(let t of state.history){let row=document.createElement('div');row.className='history-row';let left=document.createElement('span');left.textContent=`${t.side} ${t.qty} × ${t.symbol}`;left.className=t.side==='SELL'?'sell-text':'';let right=document.createElement('span');right.textContent=fmt(t.price*t.qty);row.append(left,right);box.append(row);}}
function updateAll(){seriesForChart();updateHeader();updateTrading();updatePortfolio();drawChart();}
function order(side){if(!state.pro){status('Trading is locked in the Free preview.');return;}let qty=Number(el('quantity').value);if(!Number.isSafeInteger(qty)||qty<1||qty>100000){status('Choose a whole sample quantity between 1 and 100,000.');return;}let price=lastPrice(state.symbol),amount=price*qty,symbol=state.symbol.symbol,owned=state.positions[symbol]||0;if(side==='BUY'&&amount>state.cash+1e-7){status('Not enough virtual cash for that order.');return;}if(side==='SELL'&&qty>owned){status(`You only own ${owned} virtual shares of ${symbol}.`);return;}state.cash=Math.round((state.cash+(side==='BUY'?-amount:amount))*100)/100;state.positions[symbol]=owned+(side==='BUY'?qty:-qty);state.history.unshift({side,qty,symbol,price});state.history=state.history.slice(0,20);status(`${side} simulated at ${fmt(price)}. No actual order was placed.`);safeStore();updatePortfolio();}
function status(message){el('trade-status').textContent=message;}
function setPro(value){state.pro=value;safeStore();updateAll();status(value?'Sample Pro preview enabled locally. No payment or account created.':'Free view: trading buttons disabled.');}
function chartHover(event){let geo=el('chart')._chartGeom;if(!geo)return;let rect=el('chart').getBoundingClientRect(),x=event.clientX-rect.left,index=Math.floor((x-geo.left)/geo.stride);if(index<0||index>=visibleSeries.length){el('chart-tip').hidden=true;return;}let d=visibleSeries[index],tip=el('chart-tip');tip.hidden=false;tip.textContent=`${timeLabel(d.minutes)} IST • O ${d.open.toFixed(2)} H ${d.high.toFixed(2)} L ${d.low.toFixed(2)} C ${d.close.toFixed(2)}`;tip.style.left=Math.min(Math.max(3,x-55),rect.width-180)+'px';tip.style.top='7px';}
function init(){loadStore();setupStocks();updateAll();document.querySelectorAll('.interval').forEach(button=>button.addEventListener('click',()=>{state.interval=Number(button.dataset.interval);document.querySelectorAll('.interval').forEach(b=>b.classList.toggle('active',b===button));updateAll();}));el('free-button').addEventListener('click',()=>setPro(false));el('pro-button').addEventListener('click',()=>setPro(true));el('sample-pro-link').addEventListener('click',()=>setPro(true));el('buy-button').addEventListener('click',()=>order('BUY'));el('sell-button').addEventListener('click',()=>order('SELL'));el('reset-button').addEventListener('click',()=>{if(!state.pro)return;state.cash=startBalance;state.positions={};state.history=[];safeStore();updatePortfolio();status('Sample portfolio reset.');});el('chart').addEventListener('mousemove',chartHover);el('chart').addEventListener('mouseleave',()=>el('chart-tip').hidden=true);window.addEventListener('resize',drawChart);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
